apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fashionhub-network-policy
  namespace: fashionhub
  labels:
    app: fashionhub
spec:
  podSelector:
    matchLabels:
      app: fashionhub
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: fashionhub
      ports:
        - protocol: TCP
          port: 3000
        - protocol: TCP
          port: 5000
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 3000
        - protocol: TCP
          port: 5000
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
