apiVersion: apps/v1
kind: Deployment
metadata:
  name: fashionhub-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: fashionhub
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: NODE_ENV
              value: "development"
            - name: LOG_LEVEL
              value: "debug"
